### PR TITLE
FIX Subsites + Fluent = incorrect URL segment

### PR DESCRIPTION
**Pull request by mohamedallou**
fix for issue [Subsites + Fluent = incorrect URL segment on edit #416](https://github.com/silverstripe/silverstripe-subsites/issues/416)

### CODE REVIEW

**Review by NightJar — APPROVED** [review]
Well the config change is safe, but I've not yet tested :)

**Comment by emteknetnz** [comment]
What happens if fluent is not installed? Does having the `fluentcms` in the config file cause any issues?

**Comment by dhensby** [comment]
> Does having the `fluentcms` in the config file cause any issues?

it should not

**Comment by emteknetnz** [comment]
@Midouxx would you be able to retarget/rebase this pull-request to `2.3` instead of `master`.  Reasons being is that `master` is what would later become subsites `3.0`, while what we'd want to target is `2.3` which would be used for the next patch release of subsites

**Comment by dhensby** [comment]
I've rebased this onto 2.3

**Comment by emteknetnz** [comment]
Thanks Dan.  I'll give this a smoke test later this week then look to merge

**Comment by emteknetnz** [comment]
@Midouxx 

This did not appear to fully work.  Possibly a different issue from the one originally linked on issue.  When I added a fluent locale, my subsite was no longer appeared in the url segment, e.g.

http://subsite.mydomain.test/home 

became

http://mydomain.test/home

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Need to have a better idea about issue above before this could be merged

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Pull request closed without merging**
