### PR TITLE
Rename "code" to "src" for PSR-4 consistency

### PR DESCRIPTION
**Pull request by robbieaverill**
Issue: #290

### CODE REVIEW

**Comment by dhensby** [comment]
rreeeeeeeeebase

**Comment by robbieaverill** [comment]
rreeeeeeeeebased

**Comment by tractorcow** [comment]
Again pls.

**Comment by robbieaverill** [comment]
Done, cheers

**Comment by tractorcow** [comment]
Rebase again. :)

**Comment by robbieaverill** [comment]
Heh, done again

**Pull request merged**
