### PR TITLE
ENH Use cached table list from ClassInfo

### LINKED ISSUE #563: Middleware should not make table check on each request
### Module version(s) affected

3.x

### Description

Currently, the middleware make a table check on each request. While not super expensive, it feels that this is really unecessary

image

Related issues:

https://github.com/silverstripe/silverstripe-framework/issues/11181
https://github.com/tractorcow-farm/silverstripe-fluent/issues/828

### How to reproduce

Install debugbar
Install subsite module
Check the queries:  a SHOW TABLES LIKE 'SubsiteDomain' happen in each query

### Possible Solution

Don't make the check except on dev/build:
https://github.com/tractorcow-farm/silverstripe-fluent/pull/831

Rely on the cached ClassInfo::hasTable instead which will get even better in the future
https://github.com/silverstripe/silverstripe-framework/pull/11183

### Additional Context

_No response_

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/564

### PR DESCRIPTION
**Pull request by lekoala**
## Description

Fixes https://github.com/silverstripe/silverstripe-subsites/issues/563

Using ClassInfo::hasTable, the cached data is used and avoid extra query per request

## Manual testing steps

Install debugbar
Install subsite module
Check that no extra query is made

## Issues
- https://github.com/silverstripe/silverstripe-subsites/issues/563

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Please retarget to `3` and tick the relevant checkboxes if this is ready for review.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Comment by GuySartorelli** [comment]
Ahh, there's a merge conflict - can you please resolve that?

**Comment by lekoala** [comment]
ok should be good now

**Review by GuySartorelli — APPROVED** [review]
The merge commit isn't ideal but I'll make sure to squash and merge so it should be fine. 
Thanks for doing this.

**Pull request merged**
