### PR TITLE
API Replace Extension subclasses

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/11050

### CODE REVIEW

**Review by GuySartorelli — COMMENTED** [review]
LGTM, will hold this one off for last since it has failing tests. Will rerun CI after everything else is merged.

**Comment by GuySartorelli** [comment]
CI still failing - I would have said these look unrelated, except the full kitchen sink run was passing so I'd expect this to pass now too.

**Comment by emteknetnz** [comment]
Have fixed up the unit tests

Previously there was a fairly point array assertion on extraStatics(), which was a pointless method on DataExtension. I'm not sure why it was passing in sink CI

There was also a failure based on the recently merged protected extensions PR, which I've updated to use the equivalent public API instead

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
