### PR TITLE
Added missing route to `SubsiteXHRController`

### LINKED ISSUE #203: CMS requests to SubsiteXHRController fail with 404.
I'm using `1.1.x-dev` and SilverStripe 3.2.
Navigating the CMS triggers requests to `SubsiteXHRController` which all fail with a 404.

As much as I can tell, these are triggered via JavaScript from `LeftAndMain_Subsites.js`. I think there's a route that's missing in a config file?

Adding something like this makes the problem go away:
```
Director:
  rules:
    'SubsiteXHRController': 'SubsiteXHRController'
```

Not sure if that wasn't required prior to 3.2, because on a first glance I wasn't able to find the route in previous versions?

### PR DESCRIPTION
**Pull request by bummzack**
Ensure SilverStripe 3.2 compatibility. Fixes #203

### CODE REVIEW

**Comment by dhensby** [comment]
hmm, I'm surprised we don't have a failing test... let me look into this

**Comment by bummzack** [comment]
@dhensby Because test still use auto-routing. From the 3.2 changelog: *The auto-routing is still in place for unit tests, since its a frequently used feature there*

**Comment by dhensby** [comment]
Classic!

**Comment by dhensby** [comment]
thanks :)

**Pull request merged**
