### PR TITLE
BUG Subsites selection on SubsitesVirtualPage (fixes #45 and #47)

### LINKED ISSUE #45: SubsiteVirtualPage: Only Pages from 'Main Site' selectable, no matter which Subsite is selected
From http://open.silverstripe.org/ticket/4012

Error description:

Subsites version: 0.1 - trunk-r76255

Silverstripe: 2.3.x (haven´t tested it under 2.2.x)

With the page type 'Subsites Virtual Page' it is not possible to link to any page of a subsite. No matter which Subsite you select, you can only choose from pages of the 'Main site'

How to reproduce the error:

Set up a subsite and create pages within that subsite
Go to the 'Main site' and create a new page with the page type 'Subsites Virtual Page'
From the dropdown 'Subsite' choose the subsite (not the 'Main site')
The dropdown 'Choose a page to link to' always loads the pages from the 'Main site'
How it should work: The dropdown should load the pages of the selected subsite!

Possible Fix:

There are several big bugs in subsites/javascript/SubsitesTreeDropdownField.js which cause SilverStripe? to skip that code completely and use the fallback code of saphire/javascript/TreeSelectorField.js

Function ajaxGetTree():
missing closing ")" after if-condition
non existing function used (this.getIdx())
Errors in SubsitesTreeDropdownField?.js Lines 7-10:

// This if block is necessary to maintain both 2.2 and 2.3 support
var baseURL = this.options.dropdownField.helperURLBase();
 if(baseURL.match('action_callfieldmethod') var ajaxURL =  baseURL+ '&methodName=gettree&forceValues=' + this.getIdx();
else var ajaxURL =  baseURL+ 'gettree?forceValues=' + this.getIdx();
Possible fix for errors in SubsitesTreeDropdownField?.js Lines 7-10:

// This if block is necessary to maintain both 2.2 and 2.3 support
var baseURL = this.helperURLBase();
if(baseURL.match('action_callfieldmethod')) var ajaxURL =  baseURL+ '&methodName=gettree&forceValues=' + this.inputTag.value;
else var ajaxURL =  baseURL+ 'gettree?forceValues=' + this.inputTag.value;
Function ajaxExpansion():
missing closing ")" after if-condition
wrong function is called to load the subtree (gettree)
Errors in SubsitesTreeDropdownField?.js Lines 30-31:

if(baseURL.match('action_callfieldmethod') var ajaxURL =  baseURL+ '&methodName=gettree&SubtreeRootID=' + this.getIdx();
else var ajaxURL =  baseURL+ 'gettree?SubtreeRootID=' + this.getIdx();
Possible fix for errors in SubsitesTreeDropdownField?.js Lines 30-31:

if(baseURL.match('action_callfieldmethod')) var ajaxURL =  baseURL+ '&methodName=getsubtree&SubtreeRootID=' + this.getIdx();
else var ajaxURL =  baseURL+ 'getsubtree?SubtreeRootID=' + this.getIdx();
I applied this fix to subsites 0.1 and subsites-trunk-r76255 (as the error still exists in the current trunk) under Silverstripe 2.3.0 and 2.3.1 and everything works as expected.

Can someone pleasy verify this and built it into the trunk (or even better make a new release 0.2)?

I attached the fixed script that works for me.

### PR DESCRIPTION
**Pull request by chillu**
There's still too much coupling between the two form fields, but the treedropdown can operate independently now.
This also fixes some plain broken code which uses 2.x TreeDropdown APIs, and removes usage of behaviour.js style `$$()` which was removed from 3.1.

### CODE REVIEW

**Comment by pitchandtone** [comment]
Can this get merged into 1.0 or master, we have it on a multifix branch and it would be good to get rid of that fork. https://github.com/dnadesign/silverstripe-subsites/compare/multifix

**Comment by harmoney-nikr** [comment]
Agreed, this really needs to be merged into 1.* ASAP as it's fixes a broken core feature.

**Comment by harmoney-nikr** [comment]
Any update on merging this?

**Comment by dhensby** [comment]
@harmoney-nikr this needs rebasing to be merged - though I can't comment on whether it's mergable @chillu / @tractorcow

**Comment by chillu** [comment]
Reopening against 1.0

**Pull request closed without merging**
