### PR TITLE
allow disabling filter using queryParam

### PR DESCRIPTION
**Pull request by lekoala**
It is much better than relying on global state

### CODE REVIEW

**Comment by dhensby** [comment]
what's the difference between this and #382?

**Comment by robbieaverill** [comment]
One is for FileSubsites and one for GroupSubsites. I think since the existing tests pass then it's OK, but I feel like there's something more that this change needs, e.g. if you're replacing some global state filtering there should be some code removed too?

**Comment by lekoala** [comment]
Well, the idea is to have a consistent way to disable subsite filtering using query params. sorry for using two pr for that (just much easier to do so right from github and i've been lazy)

i won't remove anything for now to keep compatibility, also sometimes you cannot easily access the query itself depending on the context.

**Comment by robbieaverill** [comment]
Thanks =)

**Pull request merged**
