### PR TITLE
Add setEmptyString to prevent error when no themes

### PR DESCRIPTION
**Pull request by RuthAdele**
To fix issue #261

### CODE REVIEW

**Comment by dhensby** [comment]
I think it's confusing for a CMS user to see a dropdown with "please select" and no options. Can we wrap this in a `if ($this->allowedThemes)` ?

**Comment by sminnee** [comment]
Yeah I think that if there are no themes, the whole dropdown should be removed from the form.

**Comment by robbieaverill** [comment]
@dhensby @sminnee we have a fix that covers those changes at #273 - do you think it qualifies as a patch update so can safely go into the 1.3 branch?

**Comment by sminnee** [comment]
@robbieaverill it's a new feature so probably needs to go into the `1` branch.

**Comment by sminnee** [comment]
Replaced with #273

**Pull request closed without merging**
