### PR TITLE
API Ensure themelist returns an array

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/328

Fixes https://github.com/silverstripe/silverstripe-subsites/actions/runs/11697085928/job/32899670628

`1) SilverStripe\Subsites\Tests\SiteTreeSubsitesTest::testThemeResolverIsUsedForSettingThemeList
TypeError: SilverStripe\View\SSViewer::set_themes(): Argument #1 ($themes) must be of type array, null given, called in /home/runner/work/silverstripe-subsites/silverstripe-subsites/src/Extensions/SiteTreeSubsites.php on line 405`

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
I prefer https://github.com/silverstripe/silverstripe-subsites/pull/611/files#r1838742589 as it feels cleaner and ensures we do always set the theme list, whereas it looks like this change could result in having an old not-relevant theme list if `$themelist` is null.

**Comment by emteknetnz** [comment]
That linked solution should still fail as it'll attempt to return null in some circumstances. This unit test started failing after the template work was merged in I think - possibly the linked solution will also fail after rebasing top of the latest work in 6? Could you double check to see if that's the case?

**Comment by GuySartorelli** [comment]
It's fixing literally this exact same error in that PR, so no it won't still fail.

**Comment by emteknetnz** [comment]
Test locally, it does fix it. Will update

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
