### PR TITLE
made duplication between subsites more robust

### PR DESCRIPTION
**Pull request by pitchandtone**
and added some extra methods so it's easier to overwrite or extend

### CODE REVIEW

**Comment by pitchandtone** [comment]
Unsure why scrutinizer is erroring. Anyone?

**Comment by tractorcow** [comment]
We need to fix the tests to not run behat from master.

**Comment by tractorcow** [comment]
Please rebase on master.

**Comment by dhensby** [comment]
ping

**Comment by tractorcow** [comment]
pong!

**Comment by pitchandtone** [comment]
Rebased.

**Comment by dhensby** [comment]
@tractorcow master tests are failing anyway, but these failures seem worse?

This change looks significant to require a test, I think

**Comment by tractorcow** [comment]
Someone needs to fix these tests... master is too fragile at the moment. =(

**Comment by pitchandtone** [comment]
@dhensby @tractorcow do you want me to look at these tests? Or have you guys already?

**Comment by tractorcow** [comment]
We'll fix the tests up later. We accept that modules running against master of framework won't pass for a while, so no need to let them block merges.

**Pull request merged**
