### PR TITLE
FIX include action when creating absolute link

### PR DESCRIPTION
**Pull request by PsukheDelos**
Hi all!

I can see this issue has been fixed in master, but was hoping to get it into the SS3 version. 😄Any thoughts? 

Happy to provide more detail if necessary.

-G

### CODE REVIEW

**Comment by robbieaverill** [comment]
This does break backwards compatibility - see example: https://eval.in/961337

**Comment by NightJar** [comment]
Hmm yeah, fair enough.
But; https://eval.in/961339

Since it's a `^3` only module, and SS3's support is for php5 only (until 3.6)...
Still, we support php7 so... ¯\\_(ツ)_/¯

**Comment by robbieaverill** [comment]
>Since it's a ^3 only module, and SS3's support is for php5 only...
...Except we support php7 from 3.6, so... ¯\(ツ)/¯

Yep, we support PHP 5.3 to PHP 7.1

**Comment by PsukheDelos** [comment]
@robbieaverill @NightJar What if I were to introduce a function called `getAbsoluteActionLink ($action = null)`? Or is that adding additional technical debt?

-G

**Comment by NightJar** [comment]
G,
At this point I think your best bet would be to rather not add the parameter to the signature, but add a hook point later before returning from the function:

```
$this->extend('updateAlternateAbsoluteLink', &$url);
return $link;
```

This way you're not causing errors for folks living in the future, nor the past, and can modify the result until your heart's content via a `DataExtension`;
e.g.

```
return Controller::join_links($link, $action);
```
(which is really all that happens when passing an `$action` param anyway)

**Comment by PsukheDelos** [comment]
Thanks @NightJar! I will close this off now. 😄

**Comment by NightJar** [comment]
Of course, you might have a touch of trouble in that this is already a `DataExtension` it seems...
But the idea is still solid.

**Comment by robbieaverill** [comment]
The other option is that we can just break semver for the sake of doing this method properly

**Pull request closed without merging**
