### PR TITLE
Excluded colon from domain field validation

### PR DESCRIPTION
**Pull request by prij**
Allow users to add port numbers to domain definition if required

### CODE REVIEW

**Comment by tractorcow** [comment]
We'll write some unit tests for these.

**Comment by dhensby** [comment]
Progress on this?

**Comment by prij** [comment]
Been time poor will try to move on it next week.

**Comment by tractorcow** [comment]
@prij you should come to the office this week and we'll write some unit tests together. :)

**Comment by wilr** [comment]
Added a test and merged in `32385e5`

**Pull request closed without merging**
